#!/usr/bin/env python3
"""跳转中控实验室 — 教学演示用，非生产系统。"""

from __future__ import annotations

import json
from datetime import datetime, timezone
from pathlib import Path

from flask import Flask, jsonify, redirect, render_template, request, Response

ROOT = Path(__file__).resolve().parent
DATA = ROOT / "data" / "config.json"

app = Flask(__name__, template_folder="templates", static_folder="static")


def load_config() -> dict:
    with DATA.open("r", encoding="utf-8") as f:
        return json.load(f)


def save_config(cfg: dict) -> None:
    cfg["updated_at"] = datetime.now(timezone.utc).astimezone().strftime("%Y-%m-%d %H:%M:%S")
    DATA.parent.mkdir(parents=True, exist_ok=True)
    with DATA.open("w", encoding="utf-8") as f:
        json.dump(cfg, f, ensure_ascii=False, indent=2)
        f.write("\n")


def render_jump_js(cfg: dict, channel: str | None = None) -> str:
    """所有入口共用的外链脚本：改这里 = 全站跳转目标一起变。"""
    landing = cfg["landing_url"]
    if channel:
        for ch in cfg.get("channels", []):
            if str(ch.get("cid")) == str(channel):
                # 本地演示：用中控自己的落地页路径
                base = request.host_url.rstrip("/")
                landing = f"{base}{ch.get('landing_path', '/land/12.html')}"
                break

    delay = int(cfg.get("delay_ms") or 800)
    stats = bool(cfg.get("stats_enabled"))
    lines = [
        "/* generated by 跳转中控实验室 — 改配置后所有入口自动生效 */",
        f"/* updated_at: {cfg.get('updated_at') or 'never'} */",
        "(function () {",
    ]
    if stats:
        lines += [
            "  console.log('[中控] 模拟统计上报');",
            f"  console.log('[中控] {cfg.get('stats_label', 'stats')}');",
        ]
    lines += [
        f"  var TARGET = {json.dumps(landing, ensure_ascii=False)};",
        f"  var DELAY = {delay};",
        "  setTimeout(function () {",
        "    window.location.href = TARGET;",
        "  }, DELAY);",
        "})();",
        "",
    ]
    return "\n".join(lines)


@app.get("/")
def home():
    return redirect("/admin/")


@app.get("/admin/")
def admin_page():
    return render_template("admin.html")


@app.get("/api/config")
def api_get_config():
    return jsonify(load_config())


@app.post("/api/config")
def api_save_config():
    body = request.get_json(force=True, silent=True) or {}
    cfg = load_config()

    if "landing_url" in body:
        cfg["landing_url"] = str(body["landing_url"]).strip()
    if "delay_ms" in body:
        cfg["delay_ms"] = max(0, int(body["delay_ms"]))
    if "back_jump_url" in body:
        cfg["back_jump_url"] = str(body["back_jump_url"]).strip()
    if "stats_enabled" in body:
        cfg["stats_enabled"] = bool(body["stats_enabled"])
    if "domains" in body and isinstance(body["domains"], list):
        cfg["domains"] = body["domains"]
    if "channels" in body and isinstance(body["channels"], list):
        cfg["channels"] = body["channels"]

    save_config(cfg)
    return jsonify({"ok": True, "config": cfg})


@app.post("/api/domains/bulk")
def api_bulk_domains():
    """批量导入入口域名：一行一个 host[,channel][,note]"""
    body = request.get_json(force=True, silent=True) or {}
    text = str(body.get("text") or "")
    default_channel = str(body.get("channel") or "12")
    cfg = load_config()
    existing = {d["host"]: d for d in cfg.get("domains", [])}

    added = 0
    for raw in text.splitlines():
        line = raw.strip()
        if not line or line.startswith("#"):
            continue
        parts = [p.strip() for p in line.replace("，", ",").split(",")]
        host = parts[0]
        channel = parts[1] if len(parts) > 1 and parts[1] else default_channel
        note = parts[2] if len(parts) > 2 else "批量导入"
        if host in existing:
            existing[host]["channel"] = channel
            existing[host]["enabled"] = True
            if len(parts) > 2:
                existing[host]["note"] = note
        else:
            existing[host] = {
                "host": host,
                "channel": channel,
                "enabled": True,
                "note": note,
            }
            added += 1

    cfg["domains"] = list(existing.values())
    save_config(cfg)
    return jsonify({"ok": True, "added": added, "total": len(cfg["domains"]), "config": cfg})


@app.get("/jump.js")
def jump_js():
    """站群外链脚本入口：所有壳站都引用这一份。"""
    cfg = load_config()
    channel = request.args.get("c")
    js = render_jump_js(cfg, channel)
    return Response(js, mimetype="application/javascript; charset=utf-8")


@app.get("/entry/")
@app.get("/entry/<path:host>")
def entry_shell(host: str = "demo-entry.local"):
    """模拟某个入口域名打开后的壳页。"""
    cfg = load_config()
    # 按 host 找渠道，找不到就用默认
    channel = "12"
    for d in cfg.get("domains", []):
        if d.get("host") == host or host.endswith(d.get("host", "")):
            channel = str(d.get("channel") or "12")
            break
    return render_template("entry.html", host=host, channel=channel, delay=cfg.get("delay_ms", 800))


@app.get("/land/<path:page>")
def land_page(page: str):
    cfg = load_config()
    return render_template(
        "land.html",
        page=page,
        back_jump_url=cfg.get("back_jump_url") or "/land/hijacked.html",
        hijacked=("hijacked" in page),
    )


@app.get("/api/preview-script")
def preview_script():
    cfg = load_config()
    channel = request.args.get("c")
    return Response(render_jump_js(cfg, channel), mimetype="text/plain; charset=utf-8")


if __name__ == "__main__":
    print("跳转中控实验室 → http://127.0.0.1:8877/admin/")
    app.run(host="127.0.0.1", port=8877, debug=False)
